<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\media\MediaInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function kamihaya_cms_media_type_media_access(MediaInterface $media, $operation, AccountInterface $account) {
  if ($operation !== 'view') {
    return AccessResult::neutral();
  }

  if ($media->access($operation)) {
    return AccessResult::neutral();
  }



  return AccessResult::neutral();
}
