<?php

/**
 * @file
 * Contains hook implementations for Kamihaya CMS Menu Icon.
 */

/**
 * Implements hook_modules_installed().
 */
function kamihaya_cms_menu_icon_modules_installed($modules, $is_syncing) {
  if (!$is_syncing) {
    $module_handler = \Drupal::service('module_handler');
    // Update menu_link_attributes settings.
    if ($module_handler->moduleExists('menu_link_attributes')) {
    	$config = \Drupal::service('config.factory')->getEditable('menu_link_attributes.config');
      $config->set('attributes', [
        'container_font_awesome_class' => [
          'label' => 'Font Awesome class',
          'description' => 'Enter font awesome classes to display icon for the menu item.',
        ],
        'class' => [
          'label' => '',
          'description' => '',
        ],
        'target' => [
          'label' => '',
          'description' => '',
          'options' => [
		      '_blank' => 'New window (_blank)',
		      '_self' => 'Same window (_self)',
		  ],
        ],
      ]);
      $config->save();
    }

    // Update fontawesome settings.
    if ($module_handler->moduleExists('fontawesome')) {
    	$config = \Drupal::service('config.factory')->getEditable('fontawesome.settings');
    	$settings = [
      	'tag' => 'i',
				'method' => 'svg',
				'load_assets' => true,
				'use_cdn' => true,
				'external_svg_location' => 'https://use.fontawesome.com/releases/v6.4.0/js/all.js',
				'use_shim' => true,
				'external_shim_location' => 'https://use.fontawesome.com/releases/v6.4.0/js/,v4-shims.js',
				'allow_pseudo_elements' => false,
				'use_solid_file' => true,
				'use_regular_file' => true,
				'use_light_file' => true,
				'use_brands_file' => true,
				'use_duotone_file' => true,
				'use_thin_file' => true,
				'external_svg_integrity' => '',
				'bypass_validation' => false,
				'use_sharpregular_file' => true,
				'use_sharplight_file' => true,
				'use_sharpsolid_file' => true,
				'use_custom_file' => true,
			];
      $config->set($settings);
      $config->save();
    }
  }
}