# Schema for the configuration files of the FlowiseApi module.
kamihaya_cms_flowise_api.settings:
  type: config_object
  label: 'FlowiseApi settings'
  mapping:
    endpoint:
      type: string
      label: 'Endpoint'
    api_key:
      type: string
      label: 'API Key'

