# Schema for the configuration files of the Document Store API module.
kamihaya_cms_document_store_api.settings:
  type: config_object
  label: 'Document Store API Settings'
  mapping:
    endpoint:
      type: string
      label: 'Endpoint'
    api_key:
      type: string
      label: 'API Key'
