<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;
use Drupal\views\Entity\View;
use Drupal\views_flipped_table\Plugin\views\style\FlippedTable;

/**
 * @file
 * hook implementation for Content type.
 */

/**
 * Implements hook_preprocess_layout().
 */
function kamihaya_cms_content_type_preprocess_layout(array &$variables) {
  $links = [];
  $anchor_links = [];
  $full_width = FALSE;
  foreach($variables['content'] as $name => &$element) {
    if ($name === 'anchor_links') {
      $anchor_links = &$element;
    }
    if (is_array($element) && array_key_exists('anchor_links', $element)) {
      $anchor_links = &$element['anchor_links'];
    }
    if (strpos($name, 'group_') !== 0 || empty($element['#id']) || empty($element['#title']) || (isset($element['#access']) && empty($element['#access']))) {
      continue;
    }
    if (!empty($element['#attributes']['class']) && in_array('full-width', $element['#attributes']['class'])) {
      $full_width = TRUE;
    }

    $links[$element['#id']] = [
      'title' => $element['#title'],
      'url' => Url::fromUserInput("#{$element['#id']}"),
    ];
  }
  if (empty($links) || empty($anchor_links)) {
    return;
  }
  $anchor_links['#links'] = $links;
  $anchor_links['#attributes']['class'] = ['anchor-links'];
  $variables['content']['anchor_links'] = $anchor_links;
  if ($full_width) {
    $variables['#attached']['html_head'][] = [
      [
        '#tag' => 'style',
        '#attributes' => [
          'type' => 'text/css',
        ],
        '#value' => 'body { overflow-x: hidden; }',
      ],
      'kamihaya_cms_content_type',
    ];
  }
}

/**
 * Implements hook_node_load().
 */
function kamihaya_cms_content_type_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  $contents = $display->getComponents();
  foreach ($contents as $name => $field) {
    if (strpos($name, 'field_') !== 0) {
      continue;
    }
    $field_definition = $node->getFieldDefinition($name);
    if ($field_definition->getType() !== 'viewsreference') {
      continue;
    }
    $default_value = $field_definition->getDefaultValueLiteral();
    $value = $node->get($name)->getValue();
    if (count($default_value) === count($value)) {
      continue;
    }
    if (!empty($value)) {
      $default_value = array_slice($default_value, count($value));
    }
    $entity_repository = \Drupal::service('entity.repository');
    foreach($default_value as $item) {
      if (empty($item) || empty($item['target_uuid']) || empty($item['display_id'])) {
        continue;
      }
      /** @var \Drupal\views\ViewEntityInterface $view */
      $view = $entity_repository->loadEntityByUuid('view', $item['target_uuid']);
      if (empty($view) || empty($view->getDisplay($item['display_id']))) {
        continue;
      }
      $item['target_id'] = $view->id();
      $value[] = $item;
    }
    $node->set($name, $value);
    $build[$name] = $node->$name->view($view_mode);
  }
  if (!in_array('anchor_links', array_keys($contents))) {
    return;
  }
  $build['anchor_links'] = [
    '#theme' => 'links',
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function kamihaya_cms_content_type_entity_extra_field_info() {
  $extra = [];
  $description = t('Kamihaya cms content type module element');
  foreach (NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->id()]['display']['anchor_links'] = [
      'label' => t('Anchor links'),
      'description' => $description,
      'weight' => 100,
      'visible' => TRUE,
    ];
  }

  return $extra;
}

/**
 * Implements hook_field_group_pre_render().
 */
function kamihaya_cms_content_type_field_group_pre_render(array &$element, $group, &$rendering_object) {
  if (empty($element)) {
    return;
  }

  $empty = FALSE;
  foreach($element as $name => &$field) {
    if (strpos($name, 'field_') !== 0 || empty($field['#field_type']) || $field['#field_type'] !== 'viewsreference') {
      continue;
    }
    $empty = TRUE;
    foreach($field as $key => $value) {
      if (!is_numeric($key)) {
        continue;
      }
      if (empty($value['contents']['#view'])) {
        continue;
      }
      $view = $value['contents']['#view'];
      if (empty($view->result)) {
        continue;
      }
      if ($view->style_plugin instanceof FlippedTable) {
        $render = Drupal::service('renderer')->render($value['contents']);
        if (strpos($render, '</tr>') === FALSE) {
          continue;
        }
      }
      $empty = FALSE;
    }
  }
  if ($empty) {
    $element['#access'] = FALSE;
  }

}
