<?php

/**
 * Implements hook_theme().
 */
function kamihaya_cms_paragraph_type_theme() {
  return [
    'paragraph__accordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__accordion_item' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__divider' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__image_link' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__link_button' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__modal_dialog' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__drawer' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__slider_item' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__slider' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__headings' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__two_col_table' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__two_col_table_row' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_layout_paragraphs_builder_formatter().
 */
function kamihaya_cms_paragraph_type_preprocess_layout_paragraphs_builder_formatter(array &$variables) {
dpm($variables);
}
