<?php

/**
 * @file
 * Primary module hooks for Kamihaya CMS Datalayer module.
 */

/**
 * Implements hook_page_attachments().
 */
function kamihaya_cms_datalayer_page_attachments(array &$attachments) {
  $active_theme = \Drupal::theme()->getActiveTheme()->getName();
  if ($active_theme === 'kamihaya_digitalagency') {
    $attachments['#attached']['library'][] = 'kamihaya_cms_datalayer/datalayer';
  }
}
